# Project information
site_name: Stormckey's Page
site_url: https://stormckey.github.io/
site_author: Stormckey
# Repository
repo_name: stormckey
repo_url: https://github.com/stormckey/stormckey.github.io

edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; stormckey

theme:
  name: material
  custom_dir: overrides
  features:
      - content.action.edit # enable the button to edit the source code of the page
      - content.action.view # enable the button to view the source code of the page
      - content.code.copy # enable the button to copy the code block
      - navigation.tabs  # enable the row of tabs under the title 
      # - navigation.sections # unfold the secondary titles to the left
      # - navigation.footer # enable the next and previous button
      - navigation.indexes # the index page will be incoperate into the tab
      - search.suggest # auto suggestion
      - search.highlight # highlight when search
      - search.share # enable share when search
      - navigation.instant # optimize loading
      - navigation.tracking # URL will change as we scroll down
      - toc.follow # the sidebar will scroll automatically following the user
      - navigation.top # button to back to the top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: Roboto Mono


plugins:
  - search
      # lang:
      #   - zh
      #   - en
  - social:
      enabled: !ENV [CI, false]
      cards: !ENV [CI, false]
  - git-revision-date-localized
  - changelog #see https://github.com/TonyCrane/mkdocs-changelog-plugin
  - tooltips
  - statistics
  - glightbox



markdown_extensions:
#enable admonition
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      # anchor_linenums: true
      # use_pygments: true
      # auto_title: true
      # line_spans: __span
      # pygments_lang_class: true
  - pymdownx.superfences # allow nest codes
#enable code config
  - pymdownx.inlinehilite #inline code highlight
  - pymdownx.snippets: #enable to embed arbitrary files
      auto_append:
          - includes/abbreviations.md
  - pymdownx.highlight:
        linenums: true

#enable button
  - attr_list  
#enable content tabs
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
#daigrams are not enabled
  - footnotes
#enable emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
#image alignment
  - md_in_html
#better list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
#abbr
  - abbr
#enable math syntax
  - pymdownx.arithmatex:
      generic: true
#enable table of content
  - toc

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github # icons to the right bottom of the page
      link: https://github.com/stormckey
    - icon: fontawesome/solid/paper-plane # icons to the right bottom of the page
      link: mailto:sortygraph@gmail.com
  alternate: # change the language, the link should point to different directories
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /
      lang: zh
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-XXXXXXXXXX

extra_css:
  - css/hint.min.css
  - css/extra.css


#enable analytics
# extra:
#   analytics: 
#     provider: google
#     property: UA-XXXXXXXX-X
#     feedback:
#       title: Was this page helpful?
#       ratings:
#         - icon: material/emoticon-happy-outline
#           name: This page was helpful
#           data: 1
#           note: >-
#             Thanks for your feedback!
#         - icon: material/emoticon-sad-outline
#           name: This page could be improved
#           data: 0
#           note: >- 
#             Thanks for your feedback! Help us improve this page by
#             using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

nav:
  - Home: 
    - index.md
  - Blog: 
    - Home: Blog/index.md
    - Blog/Build_this_website.md
    - 原型: Blog/Women_and_prototype.md
    - Blog/zsh_arg.md
    - Blog/wsl_cuda.md
    - Blog/VSCode_conda.md
    - Blog/ssh_wsl.md
    - Blog/wsl_config.md
    - Blog/VSCode-Markdown.md
    - Blog/github_profile.md
    - 启用chatGPT-academic: Blog/GPT_academic.md
    - 我的CLI工具: Blog/CLI_tools.md
    - 在Mac上使用VSCode进行C/C++调试: Blog/Mac_VSC_DEBUG.md
    - Minisql: 
    #   - Introduction: Blog/Minisql/index.md
    #   - Minisql#0: Blog/Minisql/minisql_part0.md
    #   - Minisql#1: Blog/Minisql/minisql_part1.md
      - 在docker上部署minisql环境: Blog/docker_minisql.md
  - Note:
    - Home: Note/index.md
    - 计组拾遗: Note/CO_review.md
    - DS:
      - BST,AVL,Splay: Note/DS/BST_AVL_Splay.md
      - B-Tree,B+Tree: Note/DS/B-Tree_B+Tree.md
      - Red-Black Tree: Note/DS/RBTree.md
    - Missing Semester:
      - Shell: Note/Missing Semester/Shell.md
      - Shell++: Note/Missing Semester/Shell++.md
      - Vim: Note/Missing Semester/Vim.md
      - Data: Note/Missing Semester/Data.md
      - Git: Note/Missing Semester/Git.md
      - Commandline Environment: Note/Missing Semester/commandline_env.md
  - Research:
    - Research/index.md
    - Diffusion: 
      - DDPM: Research/DDPM.md
      - DDIM: Research/DDIM.md