# Project information
site_name: Stormckey's Page
site_url: https://stormckey.github.io/
site_author: Stormckey
# Repository
repo_name: stormckey
repo_url: https://github.com/stormckey/stormckey.github.io

# The path to edit the content
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; stormckey

theme:
  name: material
  custom_dir: overrides
  favicon: icons/cat.svg # put in /docs/icons/cat.svg
  font: 
    # text: Roboto Mono
    code: Roboto Mono
  features:
      - navigation.prune
      - content.action.edit # enable the button to edit the source code of the page
      - content.action.view # enable the button to view the source code of the page
      - content.code.copy # enable the button to copy the code block
      - navigation.tabs  # enable the row of tabs under the title 
      # - navigation.sections # unfold the secondary titles to the left
      # - navigation.footer # enable the next and previous button
      - navigation.indexes # the index page will be incoperate into the tab
      - search.suggest # auto suggestion
      - search.highlight # highlight when search
      - search.share # enable share when search
      - navigation.instant # optimize loading
      - navigation.tracking # URL will change as we scroll down
      - toc.follow # the sidebar will scroll automatically following the user
      - navigation.top # button to back to the top
  palette: # my customized schema
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: P
      accent: P
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt # the github cat icon in the topright
    logo: material/cat # the cat icon in the topleft
    annotation: material/star-four-points-circle

plugins:
  - search
  - meta-manager:
      merge_tags: true
  # - social: #social card
  #     enabled: !ENV [CI, false]
  #     cards: !ENV [CI, false]
  #     cards_font: Noto Sans SC
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - offline: # enable searching offline
      enabled: !ENV [OFFLINE, false]
  - table-reader
  - changelog #see https://github.com/TonyCrane/mkdocs-changelog-plugin
  - tooltips
  - macros
  - statistics
      # page_check_metadata: statistics
  - glightbox
  - blog:
      post_url_format: "{slug}"
      blog_toc: true
      post_date_format: medium
      post_excerpt: required
      post_readtime_words_per_minute: 175



markdown_extensions:
#enable admonition
  - admonition
  - pymdownx.details # enable ??? admonition
  - pymdownx.betterem # better emphasize
  - pymdownx.superfences: # allow nest codes
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#enable code config
  - pymdownx.inlinehilite #inline code highlight
  - pymdownx.snippets: #enable to embed arbitrary files
      auto_append:
          - includes/abbreviations.md
  - pymdownx.highlight:
        linenums: true # enable line display
        line_spans: __span
        pygments_lang_class: true # detect language automatically
        anchor_linenums: true # offer line anchor
  - pymdownx.keys # render key symbols
  - pymdownx.smartsymbols
#enable button
  - attr_list  
#enable content tabs
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
#daigrams are not enabled
  - footnotes
#enable emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#image alignment
  - md_in_html
#better list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
#abbr
  - abbr
#enable math syntax
  - pymdownx.arithmatex:
      generic: true
#enable table of content
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # enable table sort
  - javascripts/tablesort.js # enable table sort
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github # icons to the right bottom of the page
      link: https://github.com/stormckey
    - icon: fontawesome/solid/paper-plane # icons to the right bottom of the page
      link: mailto:sortygraph@gmail.com
  alternate: # change the language, the link should point to different directories
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /
      lang: zh
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  analytics:
    provider: google
    property: G-XXXXXXXXXX

extra_css:
  - css/hint.min.css
  - css/extra.css


nav:
  - Home: 
    - index.md
  - Blog: 
    - blog/index.md
    # - Environment:
    #   - blog/Environment/zsh_arg.md
    #   - blog/Environment/VSCode_conda.md
    #   - blog/Environment/VSCode-Markdown.md
    #   - blog/Environment/wsl_cuda.md
    #   - blog/Environment/ssh_wsl.md
    #   - blog/Environment/Mac_VSC_DEBUG.md
    #   - blog/Environment/index.md
    #   - blog/Environment/linux_config.md
    #   - blog/Environment/CLI_tools.md
    # - Lab:
    #   - blog/Labs/index.md
    #   - blog/Labs/docker_minisql.md
    #   - blog/Labs/CN_lab2.md
    #   - blog/Labs/OS_lab3.md

    # - Minisql: 
    #   - Minisql#0: Blog/Minisql/minisql_part0.md
    #   - Minisql#1: Blog/Minisql/minisql_part1.md
    # - Fun:
    #   - Blog/Fun/index.md
    #   - 原型: Blog/Fun/Women_and_prototype.md
  #   - Cool:
  #     - Blog/Cool/index.md
  #     - Blog/Cool/GPT_academic.md
  #     - Blog/Cool/github_profile.md
  #     - Blog/Cool/Vim_standardise.md
    

  - Note:
    - Note/index.md
    - Note/CO_review.md
    # - DS:
    #   - BST,AVL,Splay: Note/ADS/BST_AVL_Splay.md
    #   - B-Tree,B+Tree: Note/ADS/B-Tree_B+Tree.md
    #   - Red-Black Tree: Note/ADS/RBTree.md
    - Missing Semester:
      - Note/Missing Semester/index.md
      - Shell: Note/Missing Semester/Shell.md
      - Vim: Note/Missing Semester/Vim.md
      - Data: Note/Missing Semester/Data.md
      - Git: Note/Missing Semester/Git.md
      - Commandline Environment: Note/Missing Semester/commandline_env.md
    - 数据建模与分析:
      - Note/Data Modeling/index.md
      - 感知机: Note/Data Modeling/Perceptron.md
      - Note/Data Modeling/KNN.md
      - 朴素贝叶斯算法: Note/Data Modeling/Naive_Bayesian.md
      - 决策树: Note/Data Modeling/Decision_Tree.md
      - 逻辑斯蒂回归: Note/Data Modeling/Logistic_Regression.md
      - Note/Data Modeling/Max_Entropy.md
      - Note/Data Modeling/Support_Vector_Machine.md
      - Note/Data Modeling/Boosting.md
      - Note/Data Modeling/Centering.md

  - Research:
    - Research/index.md
    - Diffusion Model: 
      - DDPM: Research/Diffusion Model/DDPM.md
      - DDIM: Research/Diffusion Model/DDIM.md
  
  - PeiPei:
    - PeiPei/index.md
    - PeiPei/markdown.md